language: python

python:
  - "2.7"

# command to install dependencies
install: 
  - pip install -r requirements.txt --use-mirrors --no-deps
  - pip install coveralls

# command to run tests
script:
  - coverage run --source=mooc setup.py -q nosetests

after_success:
  - coveralls
